### ISSUE TITLE
Missing blocks and items for minecraft 1.20

### ISSUE THREAD

**Issue by Jaro29** [SimonDMC/BorderHoarder#1]
Missing blocks and items for minecraft 1.20

**Comment by SimonDMC** [comment]
i already replied to you on discord but here's the explanation for why i won't update it to 1.20 again.
> my vision for the map was that every item would be obtainable within the unlockable border, but with the new armor trims it's practically impossible to find a world where you can get every single item, so a 1.20 version would either feel "incomplete" or not be possible to finish. i hope you understand :]

feel free to update the item list yourself and play on 1.20 - everything should still work - but i don't plan on supporting it.

**Comment by Jaro29** [comment]
i.e. update the list in the ItemDictionary.java file?

**Comment by SimonDMC** [comment]
wait are you talking about the border hoarder plugin (this) or the border hoarder map (https://github.com/SimonDMC/borderhoarder-map)? i assumed you were talking about the map but if you mean the plugin i can update that to 1.20, sorry about that

**Comment by Jaro29** [comment]
I meant this https://github.com/SimonDMC/BorderHoarder
If you would be so kind, I would be grateful :-)

**Comment by SimonDMC** [comment]
i apologize for my hostility, the plugin has now been updated to 1.20.4 :) you can download it from the [newest release](https://github.com/SimonDMC/BorderHoarder/releases/tag/1.1.0)!

**Comment by Jaro29** [comment]
Never mind :-) Thank you very much
